---

- include_tasks: tomcat.yml

- name: Update DuckDNS IP
  cron:
    name: Update DuckDNS IP
    minute: "*/5"
    job: "echo url=\"https://www.duckdns.org/update?domains=infra-tti&token=348f8987-8d65-4d6d-8661-0921d4eace34&ip=\" | curl -k -K -"


# - name: Instalacao do HTTPD e outros pacotes necessarios
#   yum:
#     name: [ "httpd", "httpd-devel", "apr", "apr-devel", "apr-util", "apr-util-devel", "gcc", "make", "libtool", "autoconf" ]
#     state: present

# - name: Descompactando MOD_JK
#   unarchive:
#     src: tomcat-connectors-1.2.48-src.tar.gz
#     dest: /opt/

# - name: Compilando MOD_JK e instalando no tomcat
#   script: compila_mod_jk.sh

# - name: Ativando o HTTPD para iniciar automaticamente 
#   systemd:
#     state: started
#     name: httpd
#     enabled: yes

# - name: Criando link simbolico
#   file:
#     src: /opt/apache-tomcat-8.5.81/
#     dest: /opt/tomcat
#     owner: "{{ usuario }}"
#     group: "{{ grupo }}"
#     state: link
#     follow: False

# # - name: Alterando usuario dono da pasta /opt/apache-tomcat-8.5.81/
# #   file:
# #     path: /opt/apache-tomcat-8.5.81
# #     state: directory
# #     recurse: yes
# #     owner: "{{ usuario }}"
# #     group: "{{ grupo }}"
# #     mode: '0644'

# # - name: Alterando permissoes da pasta /opt/apache-tomcat-8.5.81/bin/
# #   file:
# #     path: /opt/apache-tomcat-8.5.81/bin
# #     state: directory
# #     recurse: yes
# #     mode: '0755'

# - name: Criando servico do tomcat no systemd
#   template: 
#     src: tomcat.service.j2
#     dest: /etc/systemd/system/tomcat.service

# - name: Executando reload no systemd e ativando a unit do tomcat
#   systemd:
#     daemon_reload: yes